-- MySQL Script generated by MySQL Workbench
-- 02/05/15 17:42:13
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema wat
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wat` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `wat` ;

-- -----------------------------------------------------
-- Table `wat`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wat`.`Users` (
  `userID` INT NOT NULL,
  `userName` VARCHAR(45) NOT NULL,
  `userFullName` VARCHAR(45) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `userGender` VARCHAR(5) NOT NULL,
  `userBirthday` DATE NOT NULL,
  `userCreatedDate` DATETIME NOT NULL,
  PRIMARY KEY (`userID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wat`.`Posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wat`.`Posts` (
  `postID` INT NOT NULL,
  `postTitle` VARCHAR(45) NOT NULL,
  `postContent` MEDIUMTEXT NOT NULL,
  `postEmotionLevel` INT NOT NULL,
  `postCreatedDate` DATE NOT NULL,
  PRIMARY KEY (`postID`),
  CONSTRAINT `userID`
    FOREIGN KEY ()
    REFERENCES `wat`.`Users` ()
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wat`.`ShortDescription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wat`.`ShortDescription` (
  `descID` INT NOT NULL,
  `descContent` TEXT(250) NOT NULL,
  `descEmotionLevel` INT NOT NULL,
  `descCreatedDate` DATE NOT NULL,
  PRIMARY KEY (`descID`),
  CONSTRAINT `userID`
    FOREIGN KEY ()
    REFERENCES `wat`.`Users` ()
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
